apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJSRzFwZEhKcGVWWXdNRE02WjJod1gyZHJWMHRVVmtRMVZIbHBNMHhpV2sxSE0xTlJTVzVMTVZKMk9HZG9iekZ5WlVoTWF3PT0ifX19Cg==
type: kubernetes.io/dockerconfigjson
